services:
  dooropener:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - "${DOOROPENER_PORT:-6532}:${DOOROPENER_PORT:-6532}"
    volumes:
      - ./options.json:/app/options.json:ro
      - ./users.json:/app/users.json:rw
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${DOOROPENER_PORT:-6532}/"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 10s
    container_name: dooropener
